services:
  - type: web
    name: velvet-cakes-api
    runtime: image
    repo: https://github.com/VelvetCakes/VelvetCake
    branch: main
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: velvet-cakes-db
          property: connectionString
      - key: SuperSecretKeyForVelvetCakes1234567890!@#$%
        generateValue: true
      - key: FrontendUrl
        value: https://VelvetCakes.github.io/VelvetCake
      - key: ELINA.174@ya.ru
        value: ELINA.174@ya.ru
      - key: mdwcjwwqxniesisw
        value: mdwcjwwqxniesisw
      - key: ELINA.174@ya.ru
        value: ELINA.174@ya.ru
      - key: 1362658
        sync: false
      - key: test_vS7nrD10514a97EJJ-tTu68FnV6rIQE0Jo5jshmv3EA
        sync: false

  - type: postgresql
    name: velvet-cakes-db
    plan: free
    databaseName: velvetcakes
    ipAllowList: []